### ISSUE TITLE
Cadent site relaunch issues

### ISSUE THREAD

**Issue by ratulkhan74** [cadentcom/website-relaunch#4]
@stratofax  I have created this issue for new site relaunched I will add all the issues and errors in this issue i will get while checking the site

**Comment by ratulkhan74** [comment]
**Hero section spacing issue** 

![cadent-new-site-hero-error](https://github.com/cadentcom/website-relaunch/assets/51952371/208fcbe2-eb57-46dc-8a3f-3943c985d968)

**- Hero section top bottom space should be equal
- Hero section title need more space in bottom**

**Comment by ratulkhan74** [comment]
### **Header section issue**

![cadent-new-site-header-error](https://github.com/cadentcom/website-relaunch/assets/51952371/034872ca-3a8f-4324-89da-20b1ccb4d057)

- The site logo max-width should be 120px.
- Menu items color should be same (white).
- Space between social icons should be less.

**Comment by ratulkhan74** [comment]
**### Services section issues**

![cadent-new-site-services-error](https://github.com/cadentcom/website-relaunch/assets/51952371/09919172-065e-4260-94e0-de6956ee1a52)

- Services section need more improvement
- Service card should be same size content
- Design can be more professional

**Comment by ratulkhan74** [comment]
**### Component section**

![cadent-new-site-components-error](https://github.com/cadentcom/website-relaunch/assets/51952371/1b55b93c-6e0f-4a86-ba79-c9c10e375895)

The photo should be more small
Need slightly contrast in background color

**Comment by ratulkhan74** [comment]
**### About section**

![cadent-new-site-about-error](https://github.com/cadentcom/website-relaunch/assets/51952371/4d728a64-94bc-462b-bcb5-6e46eb1960ac)

Full section need improvement

**Comment by ratulkhan74** [comment]
### **Latest post**

- There is no difference between post title and content
- Post content length should be same

![cadent-new-site-post-error](https://github.com/cadentcom/website-relaunch/assets/51952371/078f235f-eab8-4749-857a-7d868fef4877)

**Comment by ratulkhan74** [comment]
### **Contact us section**

- The textarea field too much big
- Under the contact info too much space

![cadent-new-site-contact-error](https://github.com/cadentcom/website-relaunch/assets/51952371/11c4bc0f-5dfd-450f-8a9d-b6f2b0df88f8)

**Comment by stratofax** [comment]
@ratulkhan74 Thank you for your excellent comments! It's difficult to track each issue if they are all included in one issue thread. 

Please copy each issue above to a **new issue**. Be sure to include your screenshots -- you can simply copy and paste the links from Edit mode instead of uploading again.

**Comment by ratulkhan74** [comment]
> @ratulkhan74 Thank you for your excellent comments! It's difficult to track each issue if they are all included in one issue thread.
> 
> Please copy each issue above to a **new issue**. Be sure to include your screenshots -- you can simply copy and paste the links from Edit mode instead of uploading again.

@stratofax each comment i have created a new issue please check all issues

**Comment by stratofax** [comment]
@ratulkhan74 I checked all your issues, and added comments. Please reply with your updates. I'll close this issue, since you've successfully transferred everything to new, separate issues. Thanks!
