### ISSUE TITLE
Header section issues

### ISSUE THREAD

**Issue by ratulkhan74** [cadentcom/website-relaunch#7]
@stratofax 

- The site logo max-width should be 120px.
- Menu items color should be same (white).
- Space between social icons should be less.

![cadent-new-site-header-error](https://github.com/cadentcom/website-relaunch/assets/51952371/034872ca-3a8f-4324-89da-20b1ccb4d057)

**Comment by stratofax** [comment]
- "The site logo max-width should be 120px" seems arbitrary. Please explain

**Comment by ratulkhan74** [comment]
> * "The site logo max-width should be 120px" seems arbitrary. Please explain

logo looks too big it have 150px width you can see my screenshot that is 120px width i think it is looking much better then the 150px one

**Comment by stratofax** [comment]
@ratulkhan74 please break this up into 3 separate issues.

**Comment by stratofax** [comment]
@ratulkhan74 Each of the bullet points (above) should be a separate, independent issue:

- The site logo max-width should be 120px.
- Menu items color should be same (white).
- Space between social icons should be less.
