### ISSUE TITLE
Component section issues

### ISSUE THREAD

**Issue by ratulkhan74** [cadentcom/website-relaunch#9]
@stratofax 

- The photo should be more small
- Need slightly contrast in background color

![cadent-new-site-components-error](https://github.com/cadentcom/website-relaunch/assets/51952371/1b55b93c-6e0f-4a86-ba79-c9c10e375895)

**Comment by stratofax** [comment]
@ratulkhan74 what "Need slightly contrast in background color"? The photos? The text? Please specify.

**Comment by ratulkhan74** [comment]
> @ratulkhan74 what "Need slightly contrast in background color"? The photos? The text? Please specify.

I already specified the background color need slightly contrast like this screenshot you can see the difference

![component-ss](https://github.com/cadentcom/website-relaunch/assets/51952371/842b4bc4-cfc6-4710-b6a5-e387b06f3d63)

**Comment by stratofax** [comment]
@ratulkhan74 I have to think about this one. My concerns:

- I'm not sure I want to create a visual distinction between the Services cards and the Components, as they are both related to "what we do"
- The darker background coior reduces contrast for the body text.
- The H2 ("Components of a Winning Website" should be included in the new section, if that's what we want to do.

**Comment by ratulkhan74** [comment]
@stratofax  now the looks good coz you used background color on service card now we don't need any separation between 2 sections we can close the issue
